# Generated by Django 3.1.3 on 2020-12-21 21:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_professorinfo_departments_teach_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorinfo',
            name='departments_teach_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SE', 'SE'), ('IT', 'IT'), ('CS', 'CS')], max_length=8),
        ),
    ]
