# Generated by Django 3.1.3 on 2020-12-21 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201221_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.department'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='faculty_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.facalaty'),
        ),
    ]
