# Generated by Django 3.1.3 on 2020-12-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201221_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorinfo',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_images'),
        ),
    ]
