# Generated by Django 3.1.3 on 2020-12-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201223_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorinfo',
            name='departments_teach_to',
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=35)),
                ('course_description', models.TextField()),
                ('course_pic', models.ImageField(upload_to='courses_pics')),
                ('course_url', models.URLField()),
                ('course_slug', models.SlugField(unique=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professorinfo')),
            ],
        ),
    ]
