# Generated by Django 3.1.3 on 2020-12-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201225_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_slug',
        ),
        migrations.AddField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
