# Generated by Django 3.1.3 on 2020-12-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201225_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_slug',
            new_name='slug',
        ),
    ]
