# Generated by Django 3.1.3 on 2020-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201225_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorinfo',
            name='departments_teach_to',
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
