# Generated by Django 3.1.3 on 2020-12-25 10:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_professorinfo_departments_teach_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorinfo',
            name='departments_teach_to',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SE', 'SE'), ('CS', 'CS')], max_length=5),
        ),
    ]
