# Generated by Django 3.1.3 on 2020-12-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_professorinfo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='level',
            field=models.CharField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year'), (5, 'Fivth Year'), (6, 'Sixth Year')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
