# Generated by Django 3.1.3 on 2020-12-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_studentinfo_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
