# Generated by Django 3.1.3 on 2020-12-31 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20201227_0034'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.FileField(upload_to='students_tasks')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professorinfo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.studentinfo')),
            ],
        ),
    ]
